# config/providers/anthropic.yaml - ANTHROPIC-SPECIFIC CONFIGURATION
provider_info:
  name: "anthropic"
  display_name: "Anthropic Claude"
  type: "anthropic"
  description: "Anthropic Claude models with tool use"
  documentation: "https://docs.anthropic.com"

connection:
  api_key_env: "ANTHROPIC_API_KEY"
  base_url: "https://api.anthropic.com"
  timeout: 30
  max_retries: 3

capabilities:
  function_calling: true  # Via tool use
  streaming: true
  vision: true
  embeddings: false
  fine_tuning: false

rate_limits:
  requests_per_minute: 200
  tokens_per_minute: 50000
  max_concurrent_requests: 3

models:
  # Reasoning/creative
  claude-sonnet-4-20250514:
    display_name: "Claude Sonnet 4"
    max_tokens: 64000
    supports_functions: true
    cost_per_1k_tokens: 0.015
    
  # Fast response, can't reason though
  claude-3-5-haiku-20241022:
    display_name: "Claude Haiku 3.5"
    max_tokens: 8192
    supports_functions: true
    cost_per_1k_tokens: 0.0005
  
  # Coding monster
  claude-opus-4-20250514: # EXPENSIVE
    display_name: "Claude Opus 4"
    max_tokens: 32000
    supports_functions: true
    cost_per_1k_tokens: 0.075 # TOLD YA

node_templates:
  chat_default:
    model: "claude-3-5-haiku-20241022"
    temperature: 0.6
    max_tokens: 1500
    
  coder_default:
    model: "claude-opus-4-20250514"
    temperature: 0.2
    max_tokens: 30000

  reasoning_default:
    model: "claude-sonnet-4-20250514"
    temperature: 0.4
    max_tokens: 2000
